/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#131316',
          dim: '#131316',
          bright: '#39393c',
          'lowest': '#0e0e11',
          'low': '#1b1b1e',
          DEFAULT: '#1f1f22',
          high: '#2a2a2d',
          highest: '#353438',
        },
        'on-surface': '#e4e1e6',
        'on-surface-variant': '#d8c3ad',
        outline: {
          DEFAULT: '#a08e7a',
          variant: '#534434',
        },
        primary: {
          DEFAULT: '#ffc174',
          on: '#472a00',
          container: '#f59e0b',
          'on-container': '#613b00',
          fixed: '#ffddb8',
          'fixed-dim': '#ffb95f',
          'on-fixed': '#2a1700',
          'on-fixed-variant': '#653e00',
        },
        secondary: {
          DEFAULT: '#c6c6c7',
          on: '#2f3131',
          container: '#454747',
          'on-container': '#b4b5b5',
        },
        tertiary: {
          DEFAULT: '#ffc08e',
          on: '#4d2600',
          container: '#ff9837',
          'on-container': '#6a3700',
        },
        error: {
          DEFAULT: '#ffb4ab',
          on: '#690005',
          container: '#93000a',
          'on-container': '#ffdad6',
        },
        nest: {
          void: '#050505',
          abyss: '#0a0a0a',
          carbon: '#121215',
          slate: '#18181b',
          graphite: '#222226',
          honey: '#f59e0b',
          'honey-dim': '#d97706',
          'honey-deep': '#b45309',
          amber: '#ffc174',
          white: '#ffffff',
          'white-soft': '#f4f4f5',
          zinc: '#a1a1aa',
          'zinc-dim': '#71717a',
          'hairline': 'rgba(255,255,255,0.08)',
          'hairline-bright': 'rgba(255,255,255,0.16)',
        },
      },
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.06em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        '2xs': '0.125rem',
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '0.75rem',
        'base': '1rem',
        'lg': '1.25rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
      },
      animation: {
        'pulse-honey': 'pulse-honey 2s ease-in-out infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
      },
      keyframes: {
        'pulse-honey': {
          '0%, 100%': { boxShadow: '0 0 8px -2px rgba(245,158,11,0.5)' },
          '50%': { boxShadow: '0 0 16px -2px rgba(245,158,11,0.8)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
